- hosts: all
  gather_facts: no
  remote_user: ustudy
  become: true
  become_method: sudo
  ignore_unreachable: yes
  tasks:

  tasks:



       - name: stop auto  video
         shell: screen -d -m /bin/bash /home/ustudy/scripts/auto-sc2.sh; sleep 1


