- hosts: all
  gather_facts: no
  remote_user: ustudy
  become: true
  become_method: sudo
  ignore_unreachable: yes
  
  tasks:

              - name: create cron job
                cron:
                  name: auto-sc
                  minute: "*/5"
                  job: /bin/bash /home/ustudy/scripts/auto-sc.sh
 
